# This workflow will attempt to create the docker image and ensure that it builds correctly
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # increase in the event of changes to git submodules
          fetch-depth: 5
      - name: build-docker-image
        env:
          token: ${{ secrets.CI_TOKEN }}
        run: |
          ./CreateDockerfile.sh -t $token
